// `pnpm gen:types`: regenerate src/types/api.ts from the running API's OpenAPI schema
// (docs/07 §8). The output is committed, so building the UI never needs the API running.

import { mkdirSync, writeFileSync } from "node:fs";

import openapiTS, { astToString } from "openapi-typescript";

import { apiOrigin } from "../api-origin.mjs";

const url = new URL("/openapi.json", apiOrigin());
let ast;
try {
  ast = await openapiTS(url);
} catch (error) {
  console.error(`Could not read ${url}: is the API running? (uv run python -m prime_search.api)`);
  console.error(String(error?.cause ?? error));
  process.exit(1);
}

const header =
  "// Generated by `pnpm gen:types` from the API's /openapi.json (docs/07 §8).\n" +
  "// Do not edit by hand: change the Pydantic models, restart the API, regenerate.\n\n";
mkdirSync("src/types", { recursive: true });
writeFileSync("src/types/api.ts", header + astToString(ast));
console.log(`wrote src/types/api.ts from ${url}`);
