// Generated by `pnpm gen:types` from the API's /openapi.json (docs/07 §8).
// Do not edit by hand: change the Pydantic models, restart the API, regenerate.

export interface paths {
    "/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Start a run on a worker thread and return its id at once (docs/07 §3).
         */
        post: operations["start_run_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_run__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Events
         * @description The replay a reconnecting UI falls back to (docs/07 §9).
         */
        get: operations["get_run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/{run_id}/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description A fetched document as paragraphs, with the evidence drawn from it (docs/07 §6).
         *
         *     The document is found only as a key of the run's `documents`; `doc_id` never names a
         *     file on its own.
         */
        get: operations["get_document_docs__run_id___doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bench/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bench Questions
         * @description SearchBench questions for the preset picker (docs/07 §3). The answer key stays out.
         */
        get: operations["bench_questions_bench_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bench/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bench Summary
         * @description `reports/latest.json` as `eval.report` wrote it (docs/05 §3), or `{missing: true}`.
         */
        get: operations["bench_summary_bench_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Feedback
         * @description Thumbs, comment and flagged claims to LangSmith and `data/feedback.jsonl` (docs/05 §4).
         *
         *     `langsmith` in the response says whether LangSmith has it; the file always does.
         */
        post: operations["post_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Ui Event
         * @description UI interactions to `data/ui-events.jsonl` (docs/06 §8).
         */
        post: operations["post_ui_event_ui_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Answer
         * @description docs/02 §2.7.
         *
         *     `effective_dates`, `contradictions` and `unknowns` are separate fields rather
         *     than prose because they are what distinguishes this from the baseline's
         *     free-text answer, and the evaluators score them individually (docs/05 §2).
         */
        Answer: {
            /** Summary */
            summary: string;
            /** Body Markdown */
            body_markdown: string;
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["Claim"][];
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["Citation"][];
            /**
             * Effective Dates
             * @default []
             */
            effective_dates: string[];
            /**
             * Contradictions
             * @default []
             */
            contradictions: string[];
            /**
             * Unknowns
             * @default []
             */
            unknowns: string[];
            /** Confidence */
            confidence: number;
            /** Scope Warning */
            scope_warning?: string | null;
        };
        /**
         * BenchQuestion
         * @description A SearchBench question for the preset picker (docs/07 §3). Never the answer key.
         */
        BenchQuestion: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Domain */
            domain: string;
            /** Tier */
            tier: number;
            /** Question Type */
            question_type: string;
            /** Split */
            split: string;
        };
        /**
         * Branch
         * @description One line of enquiry in the plan (docs/02 §2.2). The root writes these as
         *     Python in a sandboxed cell (docs/03 §3).
         */
        Branch: {
            /** Branch Id */
            branch_id: string;
            /** Question */
            question: string;
            /** Hypothesis */
            hypothesis?: string | null;
            /** Rationale */
            rationale: string;
            /**
             * Source Hint
             * @enum {string}
             */
            source_hint: "primary_policy" | "coding_article" | "fda_label" | "guidance" | "news" | "any";
            /** Priority */
            priority: number;
            /**
             * Depends On
             * @default []
             */
            depends_on: string[];
        };
        /** Budget */
        Budget: {
            /**
             * Max Searches
             * @default 30
             */
            max_searches: number;
            /**
             * Max Fetches
             * @default 20
             */
            max_fetches: number;
            /**
             * Max Deep Reads
             * @default 10
             */
            max_deep_reads: number;
            /**
             * Max Agents
             * @default 6
             */
            max_agents: number;
            /**
             * Max Rounds
             * @default 3
             */
            max_rounds: number;
            /**
             * Max Tokens
             * @default 150000
             */
            max_tokens: number;
            /**
             * Max Seconds
             * @default 180
             */
            max_seconds: number;
        };
        /**
         * Citation
         * @description docs/02 §2.7. `label` is built from document metadata with missing pieces
         *     omitted, never invented (docs/04 §5).
         */
        Citation: {
            /** N */
            n: number;
            /** Evidence Id */
            evidence_id: string;
            /** Doc Id */
            doc_id: string;
            /** Url */
            url: string;
            /** Label */
            label: string;
        };
        /**
         * Claim
         * @description A node in the claim graph (docs/02 §2.5, docs/04 §4).
         *
         *     `status` is the answer to "may this be stated?": docs/04 §1 makes a coverage
         *     claim `supported` only when some backing evidence is primary or official.
         */
        Claim: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            /** Branch Id */
            branch_id: string;
            /**
             * Supported By
             * @default []
             */
            supported_by: string[];
            /**
             * Contradicted By
             * @default []
             */
            contradicted_by: string[];
            /**
             * Derived From
             * @default []
             */
            derived_from: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "contested" | "weak" | "unresolved";
            /** Confidence */
            confidence: number;
            /** Governing Date */
            governing_date?: string | null;
        };
        /**
         * CriticReport
         * @description docs/02 §2.6. The critic emits this as fenced JSON, not a native tool call
         *     (docs/01 §4), so every field has to survive a round trip through text.
         */
        CriticReport: {
            /**
             * Weak Claims
             * @default []
             */
            weak_claims: string[];
            /**
             * Missing Interpretations
             * @default []
             */
            missing_interpretations: string[];
            /**
             * Source Independence Issues
             * @default []
             */
            source_independence_issues: string[];
            /**
             * Secondary When Primary Exists
             * @default []
             */
            secondary_when_primary_exists: string[];
            /**
             * Outdated Sources
             * @default []
             */
            outdated_sources: string[];
            /**
             * Contradictions
             * @default []
             */
            contradictions: string[];
            /**
             * Recommended Searches
             * @default []
             */
            recommended_searches: components["schemas"]["SearchTask"][];
            /** Completion Probability */
            completion_probability: number;
            /** Reasoning */
            reasoning: string;
        };
        /**
         * DocView
         * @description `GET /docs/{run_id}/{doc_id}` (docs/07 §6–7), one page of paragraphs at a time.
         *
         *     `text_error` is set, with no paragraphs, when the text cannot be shown (a snippet-only
         *     document, or text that no longer matches its index); the metadata and evidence still are.
         */
        DocView: {
            document: components["schemas"]["Document"];
            /** Paragraphs */
            paragraphs: components["schemas"]["ParagraphOut"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Text Error */
            text_error?: string | null;
        };
        /**
         * Document
         * @description A fetched or snippet-only source (docs/02 §2.4).
         *
         *     `doc_id` hashes the *normalized* URL (docs/03 §13) so two agents that reach the
         *     same page by different links share one document; `url` keeps the URL as
         *     retrieved, which is what a citation renders.
         *
         *     `text_path` and `paragraph_count` stay `""`/`0` while the document is
         *     `snippet_only`: docs/02 makes both required, and a sentinel keeps the contract
         *     intact without widening the schema.
         */
        Document: {
            /** Doc Id */
            doc_id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /**
             * Source Tier
             * @enum {string}
             */
            source_tier: "primary_policy" | "official_secondary" | "professional" | "trade" | "web" | "unknown";
            /** Publisher */
            publisher?: string | null;
            /** Doc Type */
            doc_type?: string | null;
            /** Document Id External */
            document_id_external?: string | null;
            /** Effective Date */
            effective_date?: string | null;
            /** Revision Date */
            revision_date?: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Text Path
             * @default
             */
            text_path: string;
            /**
             * Paragraph Count
             * @default 0
             */
            paragraph_count: number;
            /**
             * Fetch Method
             * @enum {string}
             */
            fetch_method: "extract" | "raw_content" | "snippet_only";
        };
        /**
         * Event
         * @description One line of `runs/<run_id>/events.jsonl` (docs/02 §4, 06 §4).
         */
        Event: {
            /** Ts */
            ts: string;
            /** Run Id */
            run_id: string;
            /** Type */
            type: string;
            /** Seq */
            seq: number;
            /** Payload */
            payload?: unknown;
        };
        /**
         * Evidence
         * @description A verbatim passage that supports, contradicts or contextualizes a claim
         *     (docs/02 §2.4, rules in docs/04 §3).
         *
         *     `evidence_text` must be a verbatim substring of the paragraph `location` points
         *     at — never a paraphrase and never a search snippet. That check is what the
         *     whole evidence model rests on.
         */
        Evidence: {
            /** Evidence Id */
            evidence_id: string;
            /** Doc Id */
            doc_id: string;
            /** Branch Id */
            branch_id: string;
            /** Claim Text */
            claim_text: string;
            /** Evidence Text */
            evidence_text: string;
            location: components["schemas"]["Location"];
            /** Effective Date */
            effective_date?: string | null;
            /** Relevance */
            relevance: number;
            /** Source Quality */
            source_quality: number;
            /** Confidence */
            confidence: number;
            /**
             * Stance
             * @enum {string}
             */
            stance: "supports" | "contradicts" | "context";
        };
        /**
         * FeedbackIn
         * @description `POST /feedback` (docs/07 §7). `thumbs` maps to `user_thumbs` 1 / 0 (06 §3).
         */
        FeedbackIn: {
            /** Run Id */
            run_id: string;
            /**
             * Thumbs
             * @enum {string}
             */
            thumbs: "up" | "down";
            /** Comment */
            comment?: string | null;
            /** Claim Ids Flagged */
            claim_ids_flagged?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Location
         * @description Where a passage sits in the persisted document text (docs/02 §2.4).
         *
         *     `paragraph_index` is 0-based (docs/07 renders `?p=<index>`) and the offsets are
         *     half-open character offsets into `Document.text_path`, so
         *     `text[char_start:char_end]` is the paragraph verbatim. docs/04 §3's
         *     whitespace-normalized substring check depends on that identity holding.
         */
        Location: {
            /** Section */
            section?: string | null;
            /** Paragraph Index */
            paragraph_index: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Langsmith */
            langsmith?: boolean | null;
        };
        /**
         * ParagraphOut
         * @description A paragraph of a fetched document; `index` is what `?p=<index>` targets (07 §6).
         */
        ParagraphOut: {
            /** Index */
            index: number;
            /** Text */
            text: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Section */
            section?: string | null;
            /**
             * Boilerplate
             * @default false
             */
            boilerplate: boolean;
        };
        /**
         * QueryUnderstanding
         * @description docs/02 §2.2. `scope_warning` is set when the question asks about something
         *     outside Medicare coverage policy, which the answer must say plainly rather than
         *     answer anyway.
         */
        QueryUnderstanding: {
            /** Normalized Question */
            normalized_question: string;
            /**
             * Domain
             * @enum {string}
             */
            domain: "cgm" | "glp1" | "other";
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "eligibility" | "coding" | "coverage_pathway" | "change_detection" | "contradiction" | "out_of_scope" | "other";
            /**
             * Entities
             * @default []
             */
            entities: string[];
            /**
             * Time Sensitivity
             * @enum {string}
             */
            time_sensitivity: "low" | "medium" | "high";
            /**
             * Needs Primary Sources
             * @default true
             */
            needs_primary_sources: boolean;
            /** Scope Warning */
            scope_warning?: string | null;
        };
        /**
         * RunRecord
         * @description The persisted form of a run (docs/02 §2.1, §5).
         *
         *     Document *text* is not inline: `Document.text_path` points at
         *     runs/<run_id>/docs/<doc_id>.txt, which is what keeps a record readable and a
         *     workspace out of the root's context wholesale (docs/02 §3).
         */
        RunRecord: {
            /** Run Id */
            run_id: string;
            request: components["schemas"]["RunRequest"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Langsmith Run Url */
            langsmith_run_url?: string | null;
            /** Langsmith Trace Id */
            langsmith_trace_id?: string | null;
            plan?: components["schemas"]["SearchPlan"] | null;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["SearchTask"][];
            /**
             * Documents
             * @default {}
             */
            documents: {
                [key: string]: components["schemas"]["Document"];
            };
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["Claim"][];
            /**
             * Verdicts
             * @default []
             */
            verdicts: components["schemas"]["Verdict"][];
            /**
             * Critic Reports
             * @default []
             */
            critic_reports: components["schemas"]["CriticReport"][];
            answer?: components["schemas"]["Answer"] | null;
            usage?: components["schemas"]["Usage"];
            /**
             * Status
             * @default running
             * @enum {string}
             */
            status: "running" | "completed" | "budget_exhausted" | "failed";
            /** Error */
            error?: string | null;
        };
        /**
         * RunRequest
         * @description docs/02 §2.1. The API body, the CLI's arguments and a bench row all arrive
         *     as one of these.
         */
        RunRequest: {
            /** Question */
            question: string;
            /**
             * Mode
             * @default prime
             * @enum {string}
             */
            mode: "baseline" | "prime";
            /**
             * Depth
             * @default deep
             * @enum {string}
             */
            depth: "fast" | "deep";
            /** Question Id */
            question_id?: string | null;
            budget_override?: components["schemas"]["Budget"] | null;
            /**
             * Prompt Set
             * @default base
             * @enum {string}
             */
            prompt_set: "base" | "optimized";
        };
        /** RunStarted */
        RunStarted: {
            /** Run Id */
            run_id: string;
        };
        /**
         * RunSummary
         * @description One row of `GET /runs` (docs/07 §7), newest first.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Question */
            question: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "baseline" | "prime";
            /**
             * Depth
             * @enum {string}
             */
            depth: "fast" | "deep";
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "budget_exhausted" | "failed" | "interrupted";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            usage?: components["schemas"]["Usage"];
            /**
             * Example
             * @default false
             */
            example: boolean;
        };
        /**
         * SearchPlan
         * @description docs/02 §2.2. Also the structured-output fallback shape when the root emits
         *     no parseable code block (docs/03 §3).
         */
        SearchPlan: {
            understanding: components["schemas"]["QueryUnderstanding"];
            /** Branches */
            branches: components["schemas"]["Branch"][];
            /** Stop Criteria */
            stop_criteria: string;
            budget: components["schemas"]["Budget"];
        };
        /** SearchTask */
        SearchTask: {
            /** Task Id */
            task_id: string;
            /** Branch Id */
            branch_id: string;
            /** Round */
            round: number;
            /** Instruction */
            instruction: string;
            /**
             * Queries Hint
             * @default []
             */
            queries_hint: string[];
            /**
             * Include Domains
             * @default []
             */
            include_domains: string[];
            /** Time Range */
            time_range?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            result?: components["schemas"]["TaskResult"] | null;
        };
        /** TaskResult */
        TaskResult: {
            /** Queries Issued */
            queries_issued: string[];
            /** Documents Fetched */
            documents_fetched: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Summary */
            summary: string;
            /** Unresolved */
            unresolved: string | null;
            usage: components["schemas"]["Usage"];
        };
        /**
         * UiEventIn
         * @description `POST /ui-event` (docs/07 §7, 06 §8).
         */
        UiEventIn: {
            /** Run Id */
            run_id?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "ui.evidence_opened" | "ui.claim_flagged" | "ui.compare_toggled" | "ui.rerun";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** Usage */
        Usage: {
            /**
             * Searches
             * @default 0
             */
            searches: number;
            /**
             * Fetches
             * @default 0
             */
            fetches: number;
            /**
             * Deep Reads
             * @default 0
             */
            deep_reads: number;
            /**
             * Agents
             * @default 0
             */
            agents: number;
            /**
             * Rounds
             * @default 0
             */
            rounds: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Wall Seconds
             * @default 0
             */
            wall_seconds: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @description Judge output (docs/02 §2.6). Also the structured-output probe in `make smoke`.
         */
        Verdict: {
            /** Round */
            round: number;
            /** Sufficient */
            sufficient: boolean;
            /** Coverage */
            coverage: {
                [key: string]: "resolved" | "partial" | "unresolved";
            };
            /** Missing */
            missing: string[];
            /**
             * New Tasks
             * @default []
             */
            new_tasks: components["schemas"]["SearchTask"][];
            /** Reasoning */
            reasoning: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_run_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_run__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description docs/02 §4 event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_docs__run_id___doc_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bench_questions_bench_questions_get: {
        parameters: {
            query?: {
                split?: ("train" | "dev" | "holdout") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchQuestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bench_summary_bench_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ui_event_ui_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
